spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lol
    username: liferay
    password: liferay
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    com:
      example: debug
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
     